#! /bin/bash
FP_PARA='/opt/ml/model/input/data/cfg/predict-args.json'
weight=$(cat $FP_PARA | jq -r '.FP_WEIGHT')
img=$(cat $FP_PARA | jq -r '.FP_SOURCE')
conf=$(cat $FP_PARA | jq -r '.CONF')
name=$(cat $FP_PARA | jq -r '.NAME')
output=$(cat $FP_PARA | jq -r '.FP_OUTPUT')
echo $weight
echo $img
# python /opt/yolov5/detect.py --source $img --weights $weight --conf $conf --name $name
# cp -r /opt/yolov5/runs/detect/$name $output

python /home/model-server/yolo5-detection/detect.py --source $img --weights $weight --conf $conf --name $name
cp -r /home/model-server/yolo5-detection/runs/detect/$name $output